<a href="https://colab.research.google.com/github/Himanshu0518/NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regex
Regular expression matching

In [ ]:
import re

In [ ]:
texts = 'Hi,My name is Himanshu singh from UP . My Mobile No is 8188937945 . Elon musk is world richest person having worth of 40 million dollors His CFO No is (848)-2345-587 '
pattern = '\(\d{3}\)-\d{4}-\d{3} |\d{10}'
re.findall(pattern,texts)

['8188937945', '(848)-2345-587 ']

In [ ]:
texts = 'The gross cost of operating lease vehicles in FY2021 Q1 was $4.85 . Tesla employee count is 5400 . In previous quarter i.e. FY2020 Q4 it was $3 billion . FY2030 Q5'

In [ ]:
pattern = '\$[\0-9\.]+'
re.findall(pattern,texts)

['$4.85 . ', '$3 ']

In [ ]:
# If I do ' want this $ sign i.e capturing groups
pattern = '\$([\0-9\.]+)'
re.findall(pattern,texts)

['4.85 . ', '3 ']

In [ ]:
# FY2021Q1 ==> 4.85   FY2020Q2 ==> 3
pattern = '(FY\d{4} Q[1234])[^\$]+(\$[0-9\.]+)'
re.findall(pattern,texts)

[('FY2021 Q1', '$4.85'), ('FY2020 Q4', '$3')]


1. Extract all twitter handles from following text. Twitter handle is the text that appears after https://twitter.com/ and is a single word. Also it contains only alpha numeric characters i.e. A-Z a-z , o to 9 and underscore _

In [ ]:
text = '''
Follow our leader Elon musk on twitter here: https://twitter.com/elonmusk, more information
on Tesla's products can be found at https://www.tesla.com/. Also here are leading influencers
for tesla related news,
https://twitter.com/teslarati
https://twitter.com/dummy_tesla
https://twitter.com/dummy_2_tesla
'''
pattern = 'https:\/\/twitter.com\/([a-zA-z0-9_]+)' # todo: type your regex here

re.findall(pattern, text)

['elonmusk', 'teslarati', 'dummy_tesla', 'dummy_2_tesla']

#Tokenization

In [ ]:
corpus = "The Param Vir Chakra (PVC) is India's highest military decoration awarded for displaying distinguished acts of valor during wartime. Established on January 26, 1950, the medal is awarded to members of the Indian Armed Forces for their extraordinary bravery in the face of the enemy. The decoration is conferred for the most conspicuous bravery or some daring or pre-eminent act of valor or self-sacrifice, in the presence of the enemy, whether on land, at sea, or in the air."

In [ ]:
corpus

"The Param Vir Chakra (PVC) is India's highest military decoration awarded for displaying distinguished acts of valor during wartime. Established on January 26, 1950, the medal is awarded to members of the Indian Armed Forces for their extraordinary bravery in the face of the enemy. The decoration is conferred for the most conspicuous bravery or some daring or pre-eminent act of valor or self-sacrifice, in the presence of the enemy, whether on land, at sea, or in the air."

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
from nltk.tokenize import sent_tokenize
# paragraphs ---> sentences

In [ ]:
doc = sent_tokenize(corpus)

In [ ]:
type(doc)

list

In [ ]:
from nltk.tokenize import word_tokenize
# paragraph --> word or sentence --> word
para = doc[0]+doc[1]
words = word_tokenize(para)

In [ ]:
type(words)

list

In [ ]:
from nltk.tokenize import TreebankWordTokenizer

In [ ]:
tokenizer = TreebankWordTokenizer()
words1=tokenizer.tokenize(corpus)

# Stemming
Stemming is a natural language processing (NLP) technique used to reduce words to their base or root stem. The goal is to strip suffixes or prefixes from words, transforming them into their most basic form, known as the "stem." This process helps in improving the performance of text analysis tasks like search, indexing, and information retrieval by treating different forms of a word (e.g., "running," "runner," "ran") as the same term.

In [ ]:
words = ['eat','eating','eaten','put','putting','history']

In [ ]:
from nltk.stem import PorterStemmer

 **Port Stemmer**

In [ ]:
stemming = PorterStemmer()
for word in words:
  print(word + " --> " + stemming.stem(word))

eat --> eat
eating --> eat
eaten --> eaten
put --> put
putting --> put
history --> histori


**regexStemming**

In [ ]:
from nltk.stem import RegexpStemmer

In [ ]:
words = ['eatable','eating','eaten','puts','putting','fairly']

In [ ]:
stemmer = RegexpStemmer('ing$|s$|able$|en$')
for word in words:
  print(word + " --> " + stemmer.stem(word))

eatable --> eat
eating --> eat
eaten --> eat
puts --> put
putting --> putt
fairly --> fairly


**snowball stemming**

In [ ]:
from nltk.stem import SnowballStemmer
Snowstemmer = SnowballStemmer('english')

In [ ]:
for word in words:
  print(word + " --> " + Snowstemmer.stem(word))

eatable --> eatabl
eating --> eat
eaten --> eaten
puts --> put
putting --> put
fairly --> fair


#Lametization
(NLP) technique used to reduce words to their base or dictionary form, known as a "lemma." Unlike stemming, which often removes prefixes or suffixes without considering the context, lemmatization uses morphological analysis and vocabulary to accurately identify the intended meaning and root form of a word.

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

1. Pos - Noun-n(default)
2. Verb-v
3. adjective -a
4. adverb -r

In [ ]:
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('running',pos='v')

'run'

In [ ]:
for word in words:
  print(word + " --> " + lemmatizer.lemmatize(word,pos = 'v'))

eat --> eat
eating --> eat
eaten --> eat
put --> put
putting --> put
history --> history


**Determinnig Pos**

pos --> parts of speech tag

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
from nltk import pos_tag
# pos_tag will create a list of words into  list of tupples having (word,pos)
words = 'Ganga is our holy river'
word_list = words.split()
pos_tag(word_list)

[('Ganga', 'NNP'),
 ('is', 'VBZ'),
 ('our', 'PRP$'),
 ('holy', 'JJ'),
 ('river', 'NN')]

# Stopwords

In [ ]:
from nltk.corpus import stopwords

In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stopwords.words('english')[0:5]

['i', 'me', 'my', 'myself', 'we']

In [ ]:
corpus = "The Param Vir Chakra (PVC) is India's highest military decoration awarded for displaying distinguished acts of valor during wartime. Established on January 26, 1950, the medal is awarded to members of the Indian Armed Forces for their extraordinary bravery in the face of the enemy. The decoration is conferred for the most conspicuous bravery or some daring or pre-eminent act of valor or self-sacrifice, in the presence of the enemy, whether on land, at sea, or in the air."

In [ ]:
import re

In [ ]:
pattern = '[^a-zA-Z]'
useless = re.findall(pattern,corpus)

In [ ]:
from nltk.tokenize import sent_tokenize
sentences = sent_tokenize(corpus)

In [ ]:
stemmer = PorterStemmer()

corpus = corpus.lower()
for i in range(len(sentences)):
  words = word_tokenize(sentences[i])
  words = [stemmer.stem(word) for word in words if word not in useless and word not in stopwords.words('english') ]
  sentences[i] = ' '.join(words)

In [ ]:
sentences

["the param vir chakra pvc india 's highest militari decor award display distinguish act valor wartim",
 'establish januari 26 1950 medal award member indian arm forc extraordinari braveri face enemi',
 'the decor confer conspicu braveri dare pre-emin act valor self-sacrific presenc enemi whether land sea air']

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
corpus = corpus.lower()
for i in range(len(sentences)):
  words = word_tokenize(sentences[i])
  words = [WordNetLemmatizer().lemmatize(word,pos='v') for word in words if word not in useless and word not in stopwords.words('english') ]
  sentences[i] = ' '.join(words)

In [ ]:
sentences

["param vir chakra pvc india 's highest militari decor award display distinguish act valor wartim",
 'establish januari 26 1950 medal award member indian arm forc extraordinari braveri face enemi',
 'decor confer conspicu braveri dare pre-emin act valor self-sacrific presenc enemi whether land sea air']

# Word Emedding Techniques


**BOW**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
doc = {
    "this boy is a good boy","she is a good girl ","both boy and girl are good"
}
bow_mat = vectorizer.fit_transform(doc)
bow_array = bow_mat.toarray()
vocab = vectorizer.get_feature_names_out()
print("Vocabulary:", vocab)
print("Bag of Words Array:\n", bow_array)

Vocabulary: ['and' 'are' 'both' 'boy' 'girl' 'good' 'is' 'she' 'this']
Bag of Words Array:
 [[1 1 1 1 1 1 0 0 0]
 [0 0 0 0 1 1 1 1 0]
 [0 0 0 2 0 1 1 0 1]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
doc = {
    "this boy is a good boy","she is a good girl ","both boy and girl are good"
}
vectorizer = TfidfVectorizer()
tfidf_mat = vectorizer.fit_transform(doc)
tdidf_array = tfidf_mat.toarray()
vocab = vectorizer.get_feature_names_out()
print("Vocabalory: ",vocab)
print("TF-IDF Vector ",tdidf_array)

Vocabalory:  ['and' 'are' 'both' 'boy' 'girl' 'good' 'is' 'she' 'this']
TF-IDF Vector  [[0.4711101  0.4711101  0.4711101  0.35829137 0.35829137 0.27824521
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.4804584  0.37311881
  0.4804584  0.63174505 0.        ]
 [0.         0.         0.         0.73861611 0.         0.28680065
  0.36930805 0.         0.48559571]]


**Word2vec**:

In [ ]:
!pip install gensim

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from gensim.models import Word2Vec,KeyedVectors

In [ ]:
from sklearn.manifold import TSNE

In [ ]:
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt


In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle datasets download -d nltkdata/movie-review

Dataset URL: https://www.kaggle.com/datasets/nltkdata/movie-review
License(s): other
 71% 5.00M/7.07M [00:00<00:00, 39.3MB/s]
100% 7.07M/7.07M [00:00<00:00, 43.6MB/s]


In [ ]:
from zipfile import ZipFile


In [ ]:
df = pd.read_csv('/content/movie_review.csv')
df.head()

fold_id cv_tag  html_id  sent_id  \
0        0  cv000    29590        0   
1        0  cv000    29590        1   
2        0  cv000    29590        2   
3        0  cv000    29590        3   
4        0  cv000    29590        4   

                                                text  tag  
0  films adapted from comic books have had plenty...  pos  
1  for starters , it was created by alan moore ( ...  pos  
2  to say moore and campbell thoroughly researche...  pos  
3  the book ( or " graphic novel , " if you will ...  pos  
4  in other words , don't dismiss this film becau...  pos

In [ ]:
df.shape

(64720, 6)

In [ ]:
df['tag'].value_counts()

tag
pos    32937
neg    31783
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

fold_id    0
cv_tag     0
html_id    0
sent_id    0
text       0
tag        0
dtype: int64

In [ ]:
from nltk.stem.porter import PorterStemmer
port_stem =  PorterStemmer()

In [ ]:
import nltk
from nltk.corpus import stopwords

In [ ]:
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content = ' '.join(stemmed_content)
    return stemmed_content

In [ ]:
df['text'] = df['text'].apply(stemming)

In [ ]:
x = df['text']
Y = df['tag']

In [ ]:
x = list(x)
X = []
for i in range(len(x)):
  X.append(x[i].split())

In [ ]:
X[0]

['film',
 'adapt',
 'comic',
 'book',
 'plenti',
 'success',
 'whether',
 'superhero',
 'batman',
 'superman',
 'spawn',
 'gear',
 'toward',
 'kid',
 'casper',
 'arthous',
 'crowd',
 'ghost',
 'world',
 'never',
 'realli',
 'comic',
 'book',
 'like',
 'hell']

In [ ]:
model = Word2Vec(window=10,min_count=2,workers=4)

In [ ]:
model.build_vocab(X,progress_per=1000)

In [ ]:
model.epochs

5

In [ ]:
model.corpus_count

64720

In [ ]:
model.train(X,total_examples=model.corpus_count,epochs = model.epochs)

(3347277, 3512395)

In [ ]:
model.wv.most_similar("bad")

[('good', 0.9221997261047363),
 ('nice', 0.7972761988639832),
 ('pretti', 0.7905045747756958),
 ('realli', 0.7741670608520508),
 ('alway', 0.7691931128501892),
 ('mcgann', 0.7627395391464233),
 ('guy', 0.7615212202072144),
 ('invect', 0.7614216208457947),
 ('nadir', 0.7568144798278809),
 ('vitriol', 0.7470819354057312)]

In [ ]:
model.wv.similarity('good','nice')

0.85718477

In [ ]:
model.wv.similarity('bad','ghost')

0.44712856